### ISSUE TITLE
ros2_actions package build fails ( humble branch)

### ISSUE THREAD

**Issue by FrGe2016** [IFRA-Cranfield/ros2_RobotSimulation#5]
[ros2_action Error message_part1.txt](https://github.com/IFRA-Cranfield/ros2_RobotSimulation/files/10888412/ros2_action.Error.message_part1.txt)

**Comment by FrGe2016** [comment]
[ros2_action Error message part2.txt](https://github.com/IFRA-Cranfield/ros2_RobotSimulation/files/10888422/ros2_action.Error.message.part2.txt)

**Comment by MikelBueno** [comment]
Hi @FrGe2016,

Thanks for the comment! The issue is related to the move_group_interface_improved.h file. I copied the file from Foxy, and I forgot to adjust it to Humble. I have fixed it in the commit [here](https://github.com/IFRA-Cranfield/ros2_RobotSimulation/commit/a24fa822d8e2e17c86f7770503b7d8a5f14813fd).

Hope ros2_actions builds properly now!

Regards,
Mikel

**Comment by FrGe2016** [comment]
Thank for the correction but I have mosty the same error log.
[
I had a feelling related to this file name. I have another copy of this file that sudo copied to 
/opt/ros/humble/include/moveit/move_group_interface i took this information somehere while installing a package from source ( it was from yours)

I then moved the modified file to the /home/francois/dev_ws/src/ros2_RobotSimulation/include/ directory
I still have errors errors but not the log is shorter
[ros2_action Error message_comit_a24fa82.txt](https://github.com/IFRA-Cranfield/ros2_RobotSimulation/files/10890616/ros2_action.Error.message_comit_a24fa82.txt)

**Comment by MikelBueno** [comment]
Hi @FrGe2016, 

It seems that you have not copied the move_group_interface_improved.h file properly. The log file complains about the (c) and "Footer" elements in lines 951 and 952 of the file, and if you check the file in [here](https://github.com/IFRA-Cranfield/ros2_RobotSimulation/blob/humble/include/move_group_interface_improved.h), those do not exist.

Could you please copy the file properly, remove the ros2_actions folder in your ~/dev_ws/build and ~/dev_ws/install folders (in order to reset ros2_actions completely), colcon build again and check? That should work.

Regards,
Mikel

**Comment by FrGe2016** [comment]
It worked fine. I had a few lines missing at the end of the file.

Thanks
